apiVersion: batch/v1
kind: CronJob
metadata:
  name: delete-expired-users
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: delete-expired-users
              image: your-app-image
              command: ["node", "/app/dist/scripts/deleteExpiredUsers.js"]
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: app-env
                      key: DATABASE_URL
          restartPolicy: OnFailure
